version: '3.4'
services:
  psql:
    image: postgres:13.2-alpine
    restart: always
    container_name: my-notes-psql
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: psqlAdm1n
        POSTGRES_PASSWORD: my-notes-p2zZwd
        POSTGRES_DB: my-notes
    ports:
      - 5432:5432

  mongo:
    image: mongo
    restart: always
    container_name: my-notes-mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    restart: always
    container_name: my-notes-redis
    volumes:
      - ./redis-data:/data
    ports:
      - 6379:6379